os: linux
language: generic
dist: focal
env:
  global:
    - JOB_DELAY=500
jobs:
  include:
    - stage: "Tests"
      name: "Create custom image 1 (conflict)"
      vm:
        create:
          name: job_conflict_smok11_06
      script:
        - echo "Running Job 1"
        - sleep $JOB_DELAY
