os: linux
language: generic
dist: focal
env:
  global:
    - JOB_DELAY=180
jobs:
  include:
    - stage: "Tests"
      name: "Create custom image 1 (conflict)"
      vm:
        create:
          name: job_conflict_11jul01
      script:
        - echo "Running Job 1"
        - sleep $JOB_DELAY
        - exit 1
    - stage: "Tests"
      name: "Create custom image 2 (conflict)"
      vm:
        create:
          name: job_conflict_11jul02
      script:
        - echo "Running Job 2"
        - sleep $JOB_DELAY
        - exit 1
    - stage: "Tests"
      name: "Create unique custom image"
      vm:
        create:
          name: job_unique_11smoke03
      script:
        - echo "Running Unique Image Job"
        - sleep $JOB_DELAY
