os: linux
dist: focal
vm: #existing key
  create:
    name: my_custom_name #custom identifier string, human readable
before_install: csudo apt-get -y install libxml2-dev
addons:
  apt:
    update: true
