os: linux
language: generic
dist: focal
env:
jobs:
  include:
    - stage: "Tests"
      name: "Create custom image 1 (conflict)"
      dist: focal
      vm:
        use:
          name: my_custom_name
        size: large
            script:
              - echo "Running s390x Job 1"
