os: linux
language: generic
dist: focal
env:
  global:
    - JOB_DELAY=180
jobs:
  include:
    - stage: "Tests"
      name: "Create custom image 1 (conflict)"
      vm:
        create:
          name: job_conflict_11jul05
            - echo "Compiling..."
            - make all
            - echo "Running tests"
            - ./run_tests || exit 1  # Fails if tests fail
    - stage: "Tests"
      name: "Create custom image 2 (conflict)"
      vm:
        create:
          name: job_conflict_11jul02
      script:
        - echo "Running Job 2"
        - sleep $JOB_DELAY
        - exit 1
