os: linux
language: generic
dist: focal
env:
  - INDEX=1
jobs:
  include:
    - stage: create image
      os: linux
      dist: focal
      language: generic
      vm:
        create:
          name: new-image_11tr
      before_install:
        - sudo apt-get -y install libxml2-dev
      addons:
        apt:
          update: true
    - stage: use custom image
      vm:
        use: new-image_11tr
      script:
        - echo "Running job with custom image"
